Numpy is a fundamental library for scientiic calculation in python. it provikdes support for arrays and matrices along with a collection of Mathematical function to operate on these data structures. In this lesson,
we will cover the basices of Numpy,focusing on arrays and vectorized operations.

In [2]:
!pip install numpy

In [5]:
import numpy as np

## create array using numpy
## create a ID array

arr1=np.array([1,2,3,4,5])
print((arr1))
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
## one dimentional array
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5)  ## 1 row and 5 columns 

array([[1, 2, 3, 4, 5]])

In [ ]:
## Two dimention array
arr2=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [15]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [16]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
## Identity matrix
np.eye(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
## Attributes of numpy array

arr=np.array([[1,2,3],[4,5,6]])

print("Array:\n",arr)
print("Shape:",arr.shape) # Output:(2,3)
print("Number of dimension:",arr.ndim) #output:2
print("Size (number of element):",arr.size) # output
print("Data Type:",arr.dtype) # output :int32 (may vary based on platform)
print("Item Size (in bytes):",arr.itemsize) 

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimension: 2
Size (number of element): 6
Data Type: int64
Item Size (in bytes): 8


In [19]:
print(np.__version__)

2.3.3


In [3]:
import numpy as np
## Numpy vectorized operation
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

## element wise addition
print('Addition',arr1+arr2)

## Element wise subtraction
print("Substraction",arr1-arr2)

## Element wise multiplication
print("multiplication",arr1*arr2)

## Element wise division
print("Division",arr1/arr2)


Addition [11 22 33 44 55]
Substraction [ -9 -18 -27 -36 -45]
multiplication [ 10  40  90 160 250]
Division [0.1 0.1 0.1 0.1 0.1]


In [10]:
## Universal function
arr=np.array([2,9,4,5,6])

## square root
print(np.sort(arr))


## Exponential
print(np.exp(arr))

## sine
print(np.sin(arr))

## Natural log
print(np.log(arr))

[2 4 5 6 9]
[7.38905610e+00 8.10308393e+03 5.45981500e+01 1.48413159e+02
 4.03428793e+02]
[ 0.90929743  0.41211849 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 2.19722458 1.38629436 1.60943791 1.79175947]


In [14]:
## Array slicing and indexing
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array:\n",arr)
print("array of subarray of first column",arr[0][0])
print(arr[0][0])
print(arr[0:2,1:])


Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
array of subarray of first column 1
1
[[2 3 4]
 [6 7 8]]
