Numpy is a fundamental library for scientiic calculation in python. it provikdes support for arrays and matrices along with a collection of Mathematical function to operate on these data structures. In this lesson,
we will cover the basices of Numpy,focusing on arrays and vectorized operations.

In [1]:
!pip install numpy

   ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
    --------------------------------------- 0.3/12.8 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.8 MB 2.8 MB/s eta 0:00:05
   -- ------------------------------------- 0.8/12.8 MB 1.7 MB/s eta 0:00:07
   --- ------------------------------------ 1.0/12.8 MB 1.4 MB/s eta 0:00:09
   ---- ----------------------------------- 1.3/12.8 MB 1.3 MB/s eta 0:00:09
   ------ --------------------------------- 2.1/12.8 MB 1.7 MB/s eta 0:00:07
   ------- -------------------------------- 2.4/12.8 MB 1.8 MB/s eta 0:00:06
   -------- ------------------------------- 2.6/12.8 MB 1.8 MB/s eta 0:00:06
   --------- ------------------------------ 3.1/12.8 MB 1.7 MB/s eta 0:00:06
   ----------- ---------------------------- 3.7/12.8 MB 1.8 MB/s eta 0:00:05
   ------------- -------------------------- 4.5/12.8 MB 2.0 MB/s eta 0:00:05
   --------------- ------------------------ 5.0/12.8 MB 2.0 MB/s eta 0:00:04
   ----------

In [5]:
import numpy as np

## create array using numpy
## create a ID array

arr1=np.array([1,2,3,4,5])
print((arr1))
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
## one dimentional array
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5)  ## 1 row and 5 columns 

array([[1, 2, 3, 4, 5]])

In [ ]:
## Two dimention array
arr2=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [15]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [16]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
## Identity matrix
np.eye(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
## Attributes of numpy array

arr=np.array([[1,2,3],[4,5,6]])

print("Array:\n",arr)
print("Shape:",arr.shape) # Output:(2,3)
print("Number of dimension:",arr.ndim) #output:2
print("Size (number of element):",arr.size) # output
print("Data Type:",arr.dtype) # output :int32 (may vary based on platform)
print("Item Size (in bytes):",arr.itemsize) 

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimension: 2
Size (number of element): 6
Data Type: int64
Item Size (in bytes): 8


In [19]:
print(np.__version__)

2.3.3


In [22]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(arr)
print(arr.ndim)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
2


In [25]:
a=np.array(42)
b=np.array([1,2,3,4,5])
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3
